# Generated by Django 5.1 on 2024-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_lang',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='user language'),
        ),
    ]
