# Generated by Django 5.1 on 2024-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reminder_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='reminder days'),
        ),
    ]
