# Generated by Django 5.1 on 2024-08-24 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="price in so'm", max_digits=10, verbose_name='price'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('desc', models.TextField(verbose_name='description')),
                ('percentage', models.PositiveIntegerField(default=0, verbose_name='percentage')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_discount', to='common.media')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.discount'),
        ),
    ]
