# Generated by Django 5.1 on 2024-10-04 13:48

import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='address')),
                ('address_uz', models.TextField(null=True, verbose_name='address')),
                ('address_ru', models.TextField(null=True, verbose_name='address')),
                ('phone_number1', models.CharField(max_length=20, validators=[users.validators.phone_number_validator], verbose_name='phone number1')),
                ('phone_number2', models.CharField(max_length=20, validators=[users.validators.phone_number_validator], verbose_name='phone number2')),
                ('work_time', models.CharField(max_length=255, verbose_name='work time')),
            ],
            options={
                'verbose_name': 'contacts',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('phone_number', models.CharField(max_length=20, validators=[users.validators.phone_number_validator], verbose_name='phone number')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'Contact With Us',
                'verbose_name_plural': 'Contact with Us',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='link')),
                ('icon', models.CharField(help_text='write icon code', max_length=255, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Medias',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, verbose_name='description')),
                ('desc_uz', models.CharField(max_length=255, null=True, verbose_name='description')),
                ('desc_ru', models.CharField(max_length=255, null=True, verbose_name='description')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='AboutUsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='company.aboutus')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
            ],
            options={
                'verbose_name': 'About Us Gallery',
                'verbose_name_plural': 'About Us Galleries',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='subtitle')),
                ('subtitle_uz', models.CharField(max_length=255, null=True, verbose_name='subtitle')),
                ('subtitle_ru', models.CharField(max_length=255, null=True, verbose_name='subtitle')),
                ('bg_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banner',
            },
        ),
    ]
