# Generated by Django 5.1 on 2024-09-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='desc_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='desc_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
    ]
