# Generated by Django 5.1 on 2024-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_aboutus_desc_ru_aboutus_desc_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
