# Generated by Django 5.1 on 2024-09-28 10:44

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_banner_subtitle_ru_banner_subtitle_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_uz',
            field=models.TextField(null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number1_ru',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None, verbose_name='phone number1'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number1_uz',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None, verbose_name='phone number1'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number2_ru',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None, verbose_name='phone number2'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number2_uz',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None, verbose_name='phone number2'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='work_time_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='work time'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='work_time_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='work time'),
        ),
    ]
