# Generated by Django 5.1 on 2024-09-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_contacts_address_ru_contacts_address_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='address_uz',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number1_ru',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number1_uz',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number2_ru',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number2_uz',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='work_time_ru',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='work_time_uz',
        ),
    ]
