# Generated by Django 5.1 on 2024-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_contacts_address_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_uz',
            field=models.TextField(null=True, verbose_name='address'),
        ),
    ]
