# Generated by Django 5.1 on 2024-10-04 13:48

import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='employee count')),
                ('durations_days', models.PositiveIntegerField(default=0, verbose_name='durations days')),
                ('box_count', models.PositiveIntegerField(default=0, verbose_name='box count')),
            ],
            options={
                'verbose_name': 'Notification order',
                'verbose_name_plural': 'Notification orders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20, verbose_name='status')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='longitude')),
                ('phone_number', models.CharField(max_length=20, validators=[users.validators.phone_number_validator], verbose_name='Phone number')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('order_number', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='order number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderMinSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_sum', models.CharField(max_length=255, verbose_name='order minimum sum')),
            ],
            options={
                'verbose_name': 'Order minimum sum',
                'verbose_name_plural': 'Order minimum sum',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_visible', models.BooleanField(default=True, verbose_name='is visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.product')),
            ],
        ),
    ]
