# Generated by Django 5.1 on 2024-09-17 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='employee count')),
                ('durations_days', models.PositiveIntegerField(default=0, verbose_name='durations days')),
                ('box_count', models.PositiveIntegerField(default=0, verbose_name='box count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_orders', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification order',
                'verbose_name_plural': 'Notification orders',
            },
        ),
    ]
